### ISSUE TITLE
txBits = 0x600U

### ISSUE THREAD

**Issue by iddq** [LarsH/msp430-uart#6]
Hello,

Can I ask you what it that 6? Thank you

https://github.com/LarsH/msp430-uart/blob/a32298d7c05cd92748f681fb9e63da64abda0869/main.c#L154

**Comment by LarsH** [comment]
Hello! You should not use this code for any real purpose, it is a hack to bit-bang UART on devices that does not have hardware support for it. It was written just for fun. =)

However, here is the explanation:

txBits contains the bits to transmit. As we are bit-banging we must provide start and stop bits manually. In this case two stop bits. The binary contents of txBits is transmitted least significant bit first:

```
1 1 c7    c6 c5 c4 c3 c2 c1 c0 0
````

So 0b110 or 0x6 is the two stop bits.

73 de SA5ALZ

**Comment by iddq** [comment]
Thank you. It's clear. I've made a similar solution and I'm using PxIES for start bit syncing and three timer blocks, one for baud rate generation and the others for tx and rx clocks. 73 de HG5OAP
